import { createStore, applyMiddleware } from 'redux';
import logger from 'redux-logger';
import thunk from 'redux-thunk';
import promiseMiddleware from 'redux-promise-middleware';
import fetch from 'node-fetch';

/**
 * actions
 */
const inc = () => {
    return {
        type: "INC"
    }
}

const desc = () => {
    return {
        type: "DESC"
    }
}

const add = (num) => {
    return {
        type: "ADD",
        payload: num
    }
}

/**
 * redux-thunk
 */
const asyncAdd = () => {
    
    // http://redux.js.org/docs/recipes/ReducingBoilerplate.html#actioncreatorsjs

    // Interpreted by the thunk middleware:
    return (dispatch, getState) => {
        console.log("async Action", getState());

        fetch('https://jsonplaceholder.typicode.com/posts/4')
        .then(res => res.json())
        .then(json => dispatch(add(json.id)));
    }
}

/**
 * redux-promise-middleware
 */
const promiseFecth = () => {

    // https: //github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/chaining-actions.md
    return (dispatch) => {
        dispatch({
            type: "FETCH_POST",
            payload: fetch('https://jsonplaceholder.typicode.com/posts/1')
        })
        // Handle response in action function.
        // .then(({value, action}) => value.json())
        // .then(json => console.log("promiseFecth, ", json))
    }
}

/**
 * reducer
 * @param {*} state 
 * @param {*} action 
 */
const reducer = (state = 0, action) => {

    switch (action.type) {
        case "INC":
            return state + 1;
        case "DESC":
            return state - 1;
        case "ADD":
            return state + action.payload;
        case "ERROR":
            throw new Error();
            break;

        // auto generated by redux-promise-middleware
        case "FETCH_POST_PENDING":
        case "FETCH_POST_FULFILLED":
        case "FETCH_POST_":
        default: //return default state
            return state;
    }
}

/**
 * middlewares
 */
const middlewares = [promiseMiddleware(), thunk, logger];
const middleware = applyMiddleware(...middlewares);

// http://redux.js.org/docs/api/createStore.html#createstorereducer-preloadedstate-enhancer
let store = createStore(reducer, 10, middleware);
// Log the initial state
console.log("Initialize, ", store.getState());

// Every time the state changes, log it
// Note that subscribe() returns a function for unregistering the listener
let unsubscribe = store.subscribe(() =>
  console.log("store changed, ", store.getState())
)

store.dispatch(inc());
store.dispatch(asyncAdd());
store.dispatch(desc());
store.dispatch(promiseFecth());